--- 
backend: 
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads

collections: 
  - 
    name: work
    label: Work
    slug: "{{slug}}"
    create: true
    folder: static/_posts
    fields: 
      - 
        default: work
        label: Layout
        name: layout
        widget: hidden
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: Body
        name: body
        widget: markdown
  - 
    name: tags
    label: Tags
    slug: "{{slug}}"
    create: true
    folder: static/_tags
    fields: 
      - 
        name: tag
        label: Tag
        widget: string
