--- 
backend: 
  branch: master
  media_folder: static/uploads
  name: git-gateway
  public_folder: /uploads
  publish_mode: editorial_workflow
collections: 
  - 
    create: true
    fields: 
      - 
        default: work
        label: Layout
        name: layout
        widget: hidden
      - 
        label: Title
        name: title
        widget: string
      - 
        label: "Publish Date"
        name: date
        widget: datetime
      - 
        label: Body
        name: body
        widget: markdown
    folder: static/_posts
    label: Work
    name: work
    slug: "{{slug}}"
  - 
    files: 
      - 
        fields: 
          - 
            label: Value
            name: value
            widget: string
        file: static/tags.yml
        label: Tags
        name: tags
        widget: list
    label: Parameters
    name: Parameters
